# Generated by Django 5.0.2 on 2024-02-08 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('CursoID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30, null=True)),
                ('CostoMensual', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('InstructorID', models.AutoField(primary_key=True, serialize=False)),
                ('Dni', models.CharField(max_length=15, null=True)),
                ('Nombre', models.CharField(max_length=50, null=True)),
                ('Apellido', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Celular', models.CharField(max_length=9, null=True)),
                ('PagoMensual', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piscina',
            fields=[
                ('PiscinaID', models.AutoField(primary_key=True, serialize=False)),
                ('Nivel', models.CharField(max_length=15, null=True)),
                ('Precio', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('UsuarioID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=50, null=True)),
                ('Correo', models.EmailField(max_length=100, null=True)),
                ('Contraseña', models.CharField(max_length=50, null=True)),
                ('Tipo', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoletaPago',
            fields=[
                ('BoletaPagoID', models.AutoField(primary_key=True, serialize=False)),
                ('Monto', models.FloatField(null=True)),
                ('MetodoPago', models.CharField(max_length=12, null=True)),
                ('FechaPago', models.DateField(null=True)),
                ('Dni', models.CharField(max_length=15)),
                ('CursoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiscinaAPI.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('Dni', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Descuento', models.FloatField(null=True)),
                ('FechaInscripcion', models.DateField(null=True)),
                ('CursoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PiscinaAPI.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='InstructorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PiscinaAPI.instructor'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('ReservaID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaInicio', models.DateField(null=True)),
                ('FechaTermino', models.DateField(null=True)),
                ('FechaReserva', models.DateField(null=True)),
                ('PiscinaID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PiscinaAPI.piscina')),
                ('UsuarioID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PiscinaAPI.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='UsuarioID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PiscinaAPI.usuario'),
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('Dni', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30, null=True)),
                ('Apellido', models.CharField(max_length=40, null=True)),
                ('Celular', models.CharField(max_length=9, null=True)),
                ('UsuarioID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PiscinaAPI.usuario')),
            ],
        ),
    ]
